name: Unzip Project

on:
  workflow_dispatch:   # lets you run it manually
  push:
    paths:
      - '*.zip'        # runs when zip is uploaded

jobs:
  unzip:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Unzip file
        run: |
          unzip *.zip
          rm *.zip

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "Choot"
          git push
